#!/bin/sh
# m64 -> m24
# The source and destination cannot both be remote.
# rsync error: syntax or usage error (code 1) at main.c(1446) [Receiver=3.2.7]
# m24 -> m64
# The source and destination cannot both be remote.
# rsync error: syntax or usage error (code 1) at main.c(1446) [Receiver=3.2.7]

echo "m64 -> m24"
rsync -av m64:sd/todays m24:sd/todays

echo "m24 -> m64"
rsync -av m24:sd/todays m64:sd/todays

echo "done"
