#!/bin/sh
#
# origin: ${utils}/todays
#
# make backup as ~/.todays/yyyy-mm-dd/
# then copy it as ~/Desktop/yyyy-mm-dd/
#
# unreleased:
# - behave as `todays-ls` when no arguments given?
#

if [ $# -eq 0 ]; then
    echo "usage: $0 dir1 dir2 ..."
    echo 引数がないときは todays-ls として動作するのはどうか？
    exit 1
fi

DEST=~/.todays/`date +%F`
mkdir -p ${DEST}
gtar -cf - -h $@ | (cd ${DEST} && gtar -xf -)
rsync -a ${DEST} ~/Desktop/
