#!/bin/sh
# origin: ${utils}/todays
#
# list up folders in ~/.todays/yyyy-mm-dd/
#
# changed:
# - 2021-02-06 ~/todays -> ~/Documents/todays
# - 2021-02-06 2020 and 2021 only.
# - 2022-04-03 2021 and 2022 only again (forgot commit).

cd ~/.todays
for i in 2022-*-* 2023-*-*; do
    ls -dF1 $i/*
done
